---
title: "Untitled"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning=FALSE, message=FALSE)
```

Cluster each of the team scores and then create a dataframe.

```{r scores, echo=FALSE, fig.width=10}
library(ggplot2)

teams <- c("OCTO*", 
           "SONG", 
           "MCHO", 
           "FLUF", 
           "ROBO*", 
           "DMPS*", 
           "TGIF*", 
           "SHSR", 
           "AFB", 
           "PHSH", 
           "SLNH*", 
           "MEGA", 
           "ATOM", 
           "LL")

scores <- c(108.48, 91.03, 103.47, 103.79, 102.76, 102.52, 101.72
            , 101.49, 100.94, 99.25, 96.07, 97.28, 90.13, 88.37)

scoreCluster <- kmeans(scores, 4, nstart = 100)

df <- data.frame(teams, scores, scoreCluster$cluster)

df$tier <- df$scoreCluster.cluster

```

Plot each of the teams adjusted scores.

```{r score plot, echo=FALSE, fig.width=10}
ggplot(df, aes(reorder(teams, -scores), y = scores)) +
  geom_bar(stat="identity", aes(fill = as.factor(tier))) +
  geom_text(aes(label = scores), hjust = -.1, vjust = .4, angle = 270) +
  scale_fill_brewer(palette = "Paired") +
  scale_y_continuous(breaks = c(60, 70, 80, 90, 100, 110), 
                     minor_breaks = c(88, 92, 94, 96, 98, 102, 104, 106, 108)) +
  theme(legend.position="none", axis.text.x = element_text(angle = 270, hjust = 0, vjust = .4),
        panel.grid.major.x = element_blank(), panel.grid.minor.x = element_blank(),
        panel.grid.minor = element_line(linetype = "longdash", size = .5)) +
  labs(list(x = "Team (*Indicates championship winner)", y = "Average Adjusted Score")) +
  coord_cartesian(ylim=c(70,110))
```

Import all season data and plot out points per week to compare how teams do across an entire season.

```{r score per week, echo=FALSE, fig.width=10, fig.height=2}
all.scores <- data.frame(read.csv("scores.csv", quote = "", header = TRUE, stringsAsFactors=FALSE))

ggplot(all.scores, aes(x = Week, y = Score)) +
  geom_smooth(span = 0.5) +
  facet_grid(~Team)
```
